/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uy.proyectofinal.presentacion;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import uy.proyectofinal.excepciones.PersistenciaException;
import uy.proyectofinal.excepciones.UsuarioException;
import uy.proyectofinal.excepciones.VehiculosException;
import uy.proyectofinal.logica.FachadaLogica;
import uy.proyectofinal.logica.Usuarios;
import uy.proyectofinal.logica.Vehiculo;
import uy.proyectofinal.logica.Vehiculos;

/**
 *
 * @author Richard
 */
public class internaVehiculos extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public internaVehiculos() {
        initComponents();
        
    }
    public void listarVehiculos(){
        FachadaLogica fachada = new FachadaLogica();
        Vehiculos listaVehiculo = new Vehiculos();
        ArrayList<Vehiculo> v = new ArrayList<Vehiculo>();
        DefaultTableModel model = new DefaultTableModel();
        tdVehiculosDatos.setModel(model);
        model.addColumn("Marca");
        model.addColumn("Modelo");
        model.addColumn("Patente");
        model.addColumn("Padron");
        model.addColumn("Asientos");
        model.addColumn("KM");
        model.addColumn("Precio");
        model.addColumn("Fecha");
        model.addColumn("Disponibilidad");
        jScrollPane3.setViewportView(tdVehiculosDatos);
        //SIZE DE COLUMNAS
        if (tdVehiculosDatos.getColumnModel().getColumnCount() > 0) {
            tdVehiculosDatos.getColumnModel().getColumn(4).setMaxWidth(40);
            tdVehiculosDatos.getColumnModel().getColumn(6).setMaxWidth(40);
            //tdVehiculosDatos.getColumnModel().getColumn(8).setMaxWidth(40);
        }
        try {
          listaVehiculo = fachada.obtenerVehiculos();//OBTENGO MI LISTA
          v = listaVehiculo.getVehiculos();
         
            String[] datosVehiculos = new String[9];
            for (Vehiculo datos : v) {
                datosVehiculos[0]= datos.getMarca();
                datosVehiculos[1]= datos.getModelo();
                datosVehiculos[2]= datos.getPatente();
                datosVehiculos[3]= datos.getPadron();
                datosVehiculos[4]= datos.getCantidadAsientos();
                datosVehiculos[5]= datos.getKilometros();
                datosVehiculos[6]= datos.getPrecio();
                datosVehiculos[7]= datos.getFecha();
                datosVehiculos[8]= datos.getDisponibilidad();
                model.addRow(datosVehiculos);
            }
            
          } catch (VehiculosException ex) {
            Logger.getLogger(VentanaVehiculos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UsuarioException ex) {
            Logger.getLogger(VentanaVehiculos.class.getName()).log(Level.SEVERE, null, ex);
        
        }
    }
    public void borrarVehiculo() /*throws PersistenciaException*/{
        FachadaLogica flogica = new FachadaLogica();
        Vehiculo bVehiculo = new Vehiculo();
        int fila = tdVehiculosDatos.getSelectedRow();//Selecionar fila
        
        if (fila > -1){
            String bMarca = String.valueOf(tdVehiculosDatos.getValueAt(fila, 0));
            bVehiculo.setMarca(bMarca);
            try {
                flogica.bajaVehiculos(bVehiculo);
                fila = -1;
                JOptionPane.showMessageDialog(null,"Vehiculo " + bVehiculo.getMarca()+ " ha sido borrado"+" "+JOptionPane.INFORMATION_MESSAGE);
                listarVehiculos();
            } catch (SQLException ex) {
                Logger.getLogger(VentanaVehiculos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (PersistenciaException ex) {
                Logger.getLogger(VentanaVehiculos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tdVehiculosDatos = new javax.swing.JTable();
        btnListar = new javax.swing.JButton();
        txtModelo = new javax.swing.JTextField();
        txtPatente = new javax.swing.JTextField();
        txtPadron = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtCantAsientos = new javax.swing.JTextField();
        txtKilometros = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtPrecioAlquiler = new javax.swing.JTextField();
        btnBorrar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cboDisponibildad = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtPrecioAlquiler1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(710, 520));

        tdVehiculosDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Marca", "Modelo", "Patente", "Padron", "CantidadAsientos", "Kilometros", "Precio", "Fecha", "Disponiblididad"
            }
        ));
        jScrollPane3.setViewportView(tdVehiculosDatos);
        if (tdVehiculosDatos.getColumnModel().getColumnCount() > 0) {
            tdVehiculosDatos.getColumnModel().getColumn(4).setMaxWidth(40);
            tdVehiculosDatos.getColumnModel().getColumn(6).setMaxWidth(40);
            tdVehiculosDatos.getColumnModel().getColumn(8).setMaxWidth(40);
        }

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        txtPatente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatenteActionPerformed(evt);
            }
        });

        txtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaActionPerformed(evt);
            }
        });

        jLabel2.setText("Marca");

        jLabel3.setText("Modelo");

        jLabel4.setText("Patente");

        jLabel5.setText("Padron");

        jLabel6.setText("Cantidad de Asientos");

        jLabel7.setText("Kilometros");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel1.setText("Precio Alquiler");

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        jLabel8.setText("Disponiblidad");

        cboDisponibildad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponible", "No Disponible" }));

        jLabel9.setText("Contacto");

        jLabel10.setText("Localizacion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrecioAlquiler1)
                            .addComponent(txtPrecioAlquiler)
                            .addComponent(txtPatente)
                            .addComponent(txtModelo)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel9))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboDisponibildad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPadron)
                    .addComponent(txtCantAsientos)
                    .addComponent(txtKilometros)
                    .addComponent(jTextField1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPatente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPadron, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCantAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKilometros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPrecioAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel8))
                    .addComponent(cboDisponibildad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecioAlquiler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //public void listarVehiculo(){}
                 
    
    
    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        listarVehiculos();
        /*FachadaLogica fachada = new FachadaLogica();
        Vehiculos listaVehiculo = new Vehiculos();
        ArrayList<Vehiculo> v = new ArrayList<Vehiculo>();
        DefaultTableModel model = new DefaultTableModel();
        tdVehiculosDatos.setModel(model);
        model.addColumn("Marca");
        model.addColumn("Modelo");
        model.addColumn("Patente");
        model.addColumn("Padron");
        model.addColumn("Asientos");
        model.addColumn("KM");
        model.addColumn("Precio");
        try {
          listaVehiculo = fachada.obtenerVehiculos();//OBTENGO MI LISTA
          v = listaVehiculo.getVehiculos();
         
            String[] datosVehiculos = new String[7];
            for (Vehiculo datos : v) {
                datosVehiculos[0]= datos.getMarca();
                datosVehiculos[1]= datos.getModelo();
                datosVehiculos[2]= datos.getPatente();
                datosVehiculos[3]= datos.getPadron();
                datosVehiculos[4]= datos.getCantidadAsientos();
                datosVehiculos[5]= datos.getKilometros();
                datosVehiculos[6]= datos.getPrecio();
                model.addRow(datosVehiculos);
            }
            
          } catch (VehiculosException ex) {
            Logger.getLogger(VentanaVehiculos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UsuarioException ex) {
            Logger.getLogger(VentanaVehiculos.class.getName()).log(Level.SEVERE, null, ex);
        
        }
        */
    }//GEN-LAST:event_btnListarActionPerformed

    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            Vehiculo vehiculo = new Vehiculo();
            FachadaLogica fvehiculo = new FachadaLogica();
            
            vehiculo.setPadron(txtPadron.getText());
            vehiculo.setPatente(txtPatente.getText());
            vehiculo.setMarca(txtMarca.getText());
            vehiculo.setModelo(txtModelo.getText());
            vehiculo.setCantidadAsientos(txtCantAsientos.getText());
            vehiculo.setKilometros(txtKilometros.getText());
            vehiculo.setPrecio(txtPrecioAlquiler.getText());
            vehiculo.setDisponibilidad(cboDisponibildad.getSelectedItem().toString());
            fvehiculo.ingresarVehiculo(vehiculo);
            listarVehiculos();
            
        } catch (PersistenciaException ex) {
            Logger.getLogger(internaVehiculos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(internaVehiculos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtPatenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatenteActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        borrarVehiculo();
    }//GEN-LAST:event_btnBorrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnListar;
    private javax.swing.JComboBox<String> cboDisponibildad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tdVehiculosDatos;
    private javax.swing.JTextField txtCantAsientos;
    private javax.swing.JTextField txtKilometros;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPadron;
    private javax.swing.JTextField txtPatente;
    private javax.swing.JTextField txtPrecioAlquiler;
    private javax.swing.JTextField txtPrecioAlquiler1;
    // End of variables declaration//GEN-END:variables
}
