/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uy.proyectofinal.presentacion;

import java.awt.Container;
import javax.swing.JOptionPane;
import uy.proyectofinal.excepciones.UsuarioException;
import uy.proyectofinal.logica.FachadaLogica;
import uy.proyectofinal.logica.Usuario;
import uy.proyectofinal.presentacion.Registro;
/**
 *
 * @author pc
 */
public class VentanaLogin extends javax.swing.JFrame {
    Container contentpane;
    /**
     * Creates new form principal
     */
    public VentanaLogin() {
        initComponents();
        setTitle("HomePage");
        //setSize(1020,574);
        setLocationRelativeTo(null);
        setResizable(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jIngresar = new javax.swing.JButton();
        jRegistrarse = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtClave = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jIngresar.setBackground(new java.awt.Color(204, 255, 204));
        jIngresar.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jIngresar.setText("Ingresar");
        jIngresar.setBorder(null);
        jIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(jIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 110, 40));

        jRegistrarse.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jRegistrarse.setText("¡Registrate ahora!");
        jRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRegistrarseMouseClicked(evt);
            }
        });
        jRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegistrarseActionPerformed(evt);
            }
        });
        getContentPane().add(jRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 540, 150, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Si aun no estas registrado...");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 520, 200, 20));

        txtUsuario.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 320, -1));
        getContentPane().add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 320, 40));

        jLabel2.setForeground(new java.awt.Color(153, 255, 153));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uy/proyectofinal/imagenesDeInterface/TODO ALQUILERES2.png"))); // NOI18N
        jLabel2.setText("INGRESAR");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIngresarActionPerformed
        try{
        Usuario usuario = new Usuario();
        usuario.setNomUsuario(txtUsuario.getText());
        usuario.setClave(txtClave.getText());
        
        FachadaLogica fachada = new FachadaLogica();
        //LE PIDO A LA FACHADA LA OPERACION QUE RESUELVE I FUNCIONALIDAD, LE PASO LOS DATOS AL OBJETO DE LA LOGICA
        Boolean usuarioValido = fachada.validarIngreso(usuario);
        
        if("admin".equals(usuario.getNomUsuario()) && usuarioValido ){ //CONSULTAR POR VALIDACIONES ADMIN
            JOptionPane.showMessageDialog(this, "Bienvenido "+usuario.getNomUsuario() + " "+JOptionPane.INFORMATION_MESSAGE);

                VentanaAdminUsuario vA = new VentanaAdminUsuario();
                vA.setVisible(true);
                dispose();
        }else if(usuarioValido){
            System.out.println("EL USUARIO ES VALIDO");
            JOptionPane.showMessageDialog(this, "Bienvenido.", "TODO OK AMIGOS " ,JOptionPane.INFORMATION_MESSAGE);
            VentanaHomePage hp = new VentanaHomePage();
            hp.setVisible(true);
            dispose();
        }else{
            System.out.println("EL USUARIO NO ES VALIDO");
            JOptionPane.showMessageDialog(this, "El usuario que has introducido no coincide con ninguna cuenta", "MENSAJE DE ERROR " ,JOptionPane.INFORMATION_MESSAGE);
        }
        //CUANDO DEVULEVE TRUE REDIRIGO HACIA OTRA VENTANA
        //CUANDO DEVUELVE FALSE REDIRIGO A UN MENSAJE DICIENDO QUE EL USUARIO NO ES VALIDO
        }catch (UsuarioException ex){
            JOptionPane.showMessageDialog(null, "No se puede validar el usuario","Confirmacion" , JOptionPane.INFORMATION_MESSAGE);
       
            
            
         }
    }//GEN-LAST:event_jIngresarActionPerformed

    private void jRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegistrarseActionPerformed
        
    }//GEN-LAST:event_jRegistrarseActionPerformed

    private void jRegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRegistrarseMouseClicked
        VentanaUsuario vu = new VentanaUsuario();
        super.dispose();
        vu.setVisible(true);
        vu.setFocusable(true);           
    }//GEN-LAST:event_jRegistrarseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jIngresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jRegistrarse;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
