/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uy.proyectofinal.presentacion;

import java.awt.Graphics;
import java.awt.Image;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author pc
 */
public class VentanaPublicar extends javax.swing.JFrame {

    /**
     * Creates new form ALQUILERES
     */
    public VentanaPublicar() {
        initComponents();
        setTitle("HomePage");
        setLocationRelativeTo(null);
        setResizable(false);
       

        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/uy/proyectofinal/imagenesDeInterface/estudiopaisaje.jpg"));
        Image image = icon.getImage();
        paneleEcritorio = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        btnVehiculos1 = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        panelVentanas = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVehiculos1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnVehiculos1.setText("Vehiculos");
        btnVehiculos1.setActionCommand("");
        btnVehiculos1.setBorder(null);
        btnVehiculos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVehiculos1MouseClicked(evt);
            }
        });
        btnVehiculos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculos1ActionPerformed(evt);
            }
        });

        btnAtras.setText("Atras");
        btnAtras.setPreferredSize(new java.awt.Dimension(80, 32));
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtrasMouseClicked(evt);
            }
        });
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton3.setText("Articulos de Pesca");
        jButton3.setBorder(null);

        jButton1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton1.setText("Articulos de Camping");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        paneleEcritorio.setLayer(btnVehiculos1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneleEcritorio.setLayer(btnAtras, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneleEcritorio.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneleEcritorio.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout paneleEcritorioLayout = new javax.swing.GroupLayout(paneleEcritorio);
        paneleEcritorio.setLayout(paneleEcritorioLayout);
        paneleEcritorioLayout.setHorizontalGroup(
            paneleEcritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneleEcritorioLayout.createSequentialGroup()
                .addGroup(paneleEcritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneleEcritorioLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneleEcritorioLayout.createSequentialGroup()
                        .addGap(734, 734, 734)
                        .addGroup(paneleEcritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(btnVehiculos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(87, 87, 87))
        );
        paneleEcritorioLayout.setVerticalGroup(
            paneleEcritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneleEcritorioLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(btnVehiculos1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169)
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(paneleEcritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 590));

        javax.swing.GroupLayout panelVentanasLayout = new javax.swing.GroupLayout(panelVentanas);
        panelVentanas.setLayout(panelVentanasLayout);
        panelVentanasLayout.setHorizontalGroup(
            panelVentanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );
        panelVentanasLayout.setVerticalGroup(
            panelVentanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        getContentPane().add(panelVentanas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 710, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btnVehiculos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVehiculos1MouseClicked
        
    }//GEN-LAST:event_btnVehiculos1MouseClicked

    private void btnVehiculos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculos1ActionPerformed
        internaVehiculos iVehiculos = new internaVehiculos();
        this.panelVentanas.add(iVehiculos);
        iVehiculos.show();
    }//GEN-LAST:event_btnVehiculos1ActionPerformed

    private void btnAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseClicked
        
    }//GEN-LAST:event_btnAtrasMouseClicked

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        VentanaHomePage home = new VentanaHomePage();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.panelVentanas.removeAll();
        this.panelVentanas.repaint();
            //internaVehiculos internaV = new internaVehiculos();
            //internaV = null;
            //this.dispose();
            
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPublicar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPublicar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPublicar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPublicar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPublicar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnVehiculos1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane panelVentanas;
    private javax.swing.JDesktopPane paneleEcritorio;
    // End of variables declaration//GEN-END:variables
}
